
package sis;

import dao.StudentDao;
import java.util.ArrayList;
import java.util.Iterator;
import model.TeacherModel;
import model.Student;
import dao.AcademicDao;
import dao.ConnectionProvider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Academic;

/**
 *
 * @author AmTechGuy
 */
public class ManageGrades extends javax.swing.JFrame {

    /**
     * Creates new form ManageGrades
     */
    public ManageGrades() {
        initComponents();
//        btnAdd.setEnabled(false);
//        btnSave.setEnabled(false);
        txtTotalScore.setEditable(false);
    }
    
     public void loadTeacherName (){
         ArrayList<TeacherModel> list = AcademicDao.getAllTeacherName();
        Iterator<TeacherModel> itr = list.iterator();
        while(itr.hasNext()){
            TeacherModel teacherObj = itr.next();
            jComboTeacherName.addItem(teacherObj.getName());
        }
    }
    
    public void loadStudentName(){
        ArrayList<Student> list = AcademicDao.getAllStudentName();
        Iterator<Student> itr = list.iterator();
        while(itr.hasNext()){
            Student studentObj = itr.next();
            jComboStudentName.addItem(studentObj.getName());
        }
    }
   
    
    
     public void loadStudentId(){
        ArrayList<Student> list = StudentDao.getAllStudentsID();
        Iterator<Student> itr = list.iterator();
        while(itr.hasNext()){
            Student studentObj = itr.next();
            jComboStudentID.addItem(studentObj.getStudentId());
        }
    }
     public void clear(){
         txtMath.setText("");
         txtComputer.setText("");
         txtPhysics.setText("");
         txtChemistry.setText("");
         txtFutherMath.setText("");
         txtEnglish.setText("");
         txtEconomics.setText("");
         txtGeography.setText("");
         txtIrs.setText("");
         txtAgric.setText("");
         txtTotalScore.setText("");
     }
     
     public void validates(){
         String math = txtMath.getText();
         String computer = txtComputer.getText();
         String physics = txtPhysics.getText();
         String chemistry = txtChemistry.getText();
         String further = txtFutherMath.getText();
         String english = txtEnglish.getText();
         String economics = txtEconomics.getText();
         String geography = txtGeography.getText();
         String irs = txtIrs.getText();
         String agric = txtAgric.getText();
         String score = txtTotalScore.getText();
         
         if(!math.equals("") && !computer.equals("") && !physics.equals("") 
                 && !chemistry.equals("") && !further.equals("") && !english.equals("") 
                 && !economics.equals("") && !geography.equals("") && !irs.equals("")
                 && !agric.equals("") && !score.equals("")){
             btnAdd.setEnabled(true);
             btnSave.setEnabled(true);
         }
         else {
             btnAdd.setEnabled(false);
             btnSave.setEnabled(false);
         }
     }
    public void computeScores() {
    try {
        int math = Integer.parseInt(txtMath.getText());
        int computer = Integer.parseInt(txtComputer.getText());
        int physics = Integer.parseInt(txtPhysics.getText());
        int chemistry = Integer.parseInt(txtChemistry.getText());
        int further = Integer.parseInt(txtFutherMath.getText());
        int english = Integer.parseInt(txtEnglish.getText());
        int economics = Integer.parseInt(txtEconomics.getText());
        int geography = Integer.parseInt(txtGeography.getText());
        int irs = Integer.parseInt(txtIrs.getText());
        int agric = Integer.parseInt(txtAgric.getText());

        int totalScore = math + computer + physics + chemistry + further + english + economics
                + geography + irs + agric;

        String score = String.format("%d", totalScore);
        txtTotalScore.setText(score);
    } catch (NumberFormatException e) {
        txtTotalScore.setText("Invalid input");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboTeacherName = new javax.swing.JComboBox<>();
        jComboStudentID = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboStudentName = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboLevel = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtMath = new javax.swing.JTextField();
        txtComputer = new javax.swing.JTextField();
        txtPhysics = new javax.swing.JTextField();
        txtChemistry = new javax.swing.JTextField();
        txtFutherMath = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        txtEconomics = new javax.swing.JTextField();
        txtGeography = new javax.swing.JTextField();
        txtIrs = new javax.swing.JTextField();
        txtAgric = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtTotalScore = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jComboRemarks = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Information System");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1284, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imagesIcon.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        jLabel7.setText("Logout");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Register Student");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mark Attendance");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Academic Record");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View Academic Records");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("View Report/Complains");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("View Registered Teachers");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, 278, 705));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setText("Teacher Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 97, -1, -1));

        jComboTeacherName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        getContentPane().add(jComboTeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 97, 190, -1));

        jComboStudentID.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        getContentPane().add(jComboStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 97, 190, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setText("Student ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 100, -1, -1));

        jComboStudentName.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        getContentPane().add(jComboStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 143, 190, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setText("Student Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 153, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setText("Student Level");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 153, -1, -1));

        jComboLevel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jComboLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Creche", "Nursery", "Primary 1", "Primary 2", "Primary 3", "Primary 4", "Primary 5", "JSS 1", "JSS 2", "JSS 3", "SSS 1", "SSS 2", "SSS 3" }));
        getContentPane().add(jComboLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 143, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel14.setText("Mathematics");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 199, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel17.setText("Computer Sci.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 252, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setText("Physics");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 308, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setText("Chemistry");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 354, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel27.setText("Futher Math");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 404, -1, -1));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 485, -1, -1));

        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 485, -1, -1));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 485, -1, -1));

        txtMath.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMathKeyReleased(evt);
            }
        });
        getContentPane().add(txtMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 199, 190, -1));

        txtComputer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtComputer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComputerKeyReleased(evt);
            }
        });
        getContentPane().add(txtComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 252, 190, -1));

        txtPhysics.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtPhysics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhysicsKeyReleased(evt);
            }
        });
        getContentPane().add(txtPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 297, 190, -1));

        txtChemistry.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtChemistry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChemistryKeyReleased(evt);
            }
        });
        getContentPane().add(txtChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 351, 190, -1));

        txtFutherMath.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFutherMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFutherMathKeyReleased(evt);
            }
        });
        getContentPane().add(txtFutherMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 401, 190, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher Name", "Student ID", "Student Name", "Student Level", "Mathematics", "Computer Sci", "Physics", "Chemistry", "Further Math", "English", "Economics", "Geography", "IRS", "Agric", "Total Score", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 528, 851, 123));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel29.setText("Geography");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(743, 300, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel30.setText("Agric");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 404, -1, -1));

        txtEnglish.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnglishKeyReleased(evt);
            }
        });
        getContentPane().add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 192, 190, -1));

        txtEconomics.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtEconomics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEconomicsKeyReleased(evt);
            }
        });
        getContentPane().add(txtEconomics, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 252, 190, -1));

        txtGeography.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtGeography.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGeographyKeyReleased(evt);
            }
        });
        getContentPane().add(txtGeography, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 297, 190, -1));

        txtIrs.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtIrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIrsKeyReleased(evt);
            }
        });
        getContentPane().add(txtIrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 347, 190, -1));

        txtAgric.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtAgric.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgricKeyReleased(evt);
            }
        });
        getContentPane().add(txtAgric, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 401, 190, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel31.setText("English");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 199, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel32.setText("Economics");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 255, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel33.setText("IRS");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 351, -1, -1));

        btnSave.setBackground(new java.awt.Color(0, 51, 102));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1089, 655, -1, -1));

        txtTotalScore.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTotalScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalScoreMouseClicked(evt);
            }
        });
        txtTotalScore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalScoreKeyReleased(evt);
            }
        });
        getContentPane().add(txtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 440, 190, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel28.setText("Total Score");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 440, -1, -1));

        jComboRemarks.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jComboRemarks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Very Good", "Good", "Fair", "Poor", "Very Poor", " " }));
        getContentPane().add(jComboRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 440, 190, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setText("Remarks");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadTeacherName();
        loadStudentId();
        loadStudentName();
        
    }//GEN-LAST:event_formComponentShown

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String teacherName = jComboTeacherName.getSelectedItem().toString();
        String studentId = jComboStudentID.getSelectedItem().toString();
        String studentName = jComboStudentName.getSelectedItem().toString();
        String level = jComboLevel.getSelectedItem().toString();
        String math = txtMath.getText();
        String computer = txtComputer.getText();
        String physics = txtPhysics.getText();
        String chemistry = txtChemistry.getText();
        String further = txtFutherMath.getText();
        String english = txtEnglish.getText();
        String economics = txtEconomics.getText();
        String geography = txtGeography.getText();
        String irs = txtIrs.getText();
        String agric = txtAgric.getText();
        String total = txtTotalScore.getText();
        String remarks = jComboRemarks.getSelectedItem().toString();
        try{
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Object [] obj = new Object[16];
            obj[0] = teacherName;
            obj[1] = studentId;
            obj[2] = studentName;
            obj[3] = level;
            obj[4] = math;
            obj[5] = computer;
            obj[6] = physics;
            obj[7] = chemistry;
            obj[8] = further;
            obj[9] = english;
            obj[10] = economics;
            obj[11] = geography;
            obj[12] = irs;
            obj[13] = agric;
            obj[14] = total;
            obj[15] = remarks;
            
            model.addRow(obj);
            clear();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        Academic record = new Academic();
        try{
        String query = "insert into academics(techerName, studentId, studentName, studentLevel,"
                + " mathematics, computerSci, physics, chemistry, furtherMath, english, economics, geography, "
                + "irs, agric, total, remarks) "
                + "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
             Connection connection = ConnectionProvider.getCon();
             PreparedStatement ps = connection.prepareStatement(query);
             
        for(int i = 0; i<jTable1.getRowCount(); i++){
            
            ps.setString(1, model.getValueAt(i, 0).toString());
            ps.setString(2, model.getValueAt(i, 1).toString());
            ps.setString(3, model.getValueAt(i, 2).toString());
            ps.setString(4, model.getValueAt(i, 3).toString());
            ps.setString(5, model.getValueAt(i, 4).toString());
            ps.setString(6, model.getValueAt(i, 5).toString());
            ps.setString(7, model.getValueAt(i, 6).toString());
            ps.setString(8, model.getValueAt(i, 7).toString());
            ps.setString(9, model.getValueAt(i, 8).toString());
            ps.setString(10, model.getValueAt(i, 9).toString());
            ps.setString(11, model.getValueAt(i, 10).toString());
            ps.setString(12, model.getValueAt(i, 11).toString());
            ps.setString(13, model.getValueAt(i, 12).toString());
            ps.setString(14, model.getValueAt(i, 13).toString());
            ps.setString(15, model.getValueAt(i, 14).toString());
            ps.setString(16, model.getValueAt(i, 15).toString());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Records Saved!!");
            
//               record.setTeacherName(model.getValueAt(i, 0).toString());
//               record.setStudentId(model.getValueAt(i, 1).toString());
//               record.setStudentName(model.getValueAt(i, 2).toString());
//               record.setStudentLevel(model.getValueAt(i, 3).toString());
//               record.setMath(model.getValueAt(i, 4).toString());
//               record.setComputer(model.getValueAt(i, 5).toString());
//               record.setPhysics(model.getValueAt(i, 6).toString());
//               record.setChemistry(model.getValueAt(i, 7).toString());
//               record.setFurther(model.getValueAt(i, 8).toString());
//               record.setEnglish(model.getValueAt(i, 9).toString());
//               record.setEconomics(model.getValueAt(i, 10).toString());
//               record.setGeography(model.getValueAt(i, 11).toString());
//               record.setIrs(model.getValueAt(i, 12).toString());
//               record.setAgric(model.getValueAt(i, 13).toString());
//               record.setTotal(model.getValueAt(i, 14).toString());
//               record.setRemarks(model.getValueAt(i,15).toString());
//               
//               AcademicDao.save(record);
//               dispose();
        }
               setVisible(false);
               new ManageGrades().setVisible(true);
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtMathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMathKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtMathKeyReleased

    private void txtComputerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComputerKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtComputerKeyReleased

    private void txtPhysicsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhysicsKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtPhysicsKeyReleased

    private void txtChemistryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChemistryKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtChemistryKeyReleased

    private void txtFutherMathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFutherMathKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtFutherMathKeyReleased

    private void txtTotalScoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalScoreKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtTotalScoreKeyReleased

    private void txtEnglishKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnglishKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtEnglishKeyReleased

    private void txtEconomicsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEconomicsKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtEconomicsKeyReleased

    private void txtGeographyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeographyKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtGeographyKeyReleased

    private void txtIrsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIrsKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtIrsKeyReleased

    private void txtAgricKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgricKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtAgricKeyReleased

    private void txtTotalScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalScoreMouseClicked
        // TODO add your handling code here:
        computeScores();
    }//GEN-LAST:event_txtTotalScoreMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         model.setRowCount(0);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            if (jTable1.getSelectedRow() != -1){
                model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setVisible(false);
        new TeacherDashBoard().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new StudentRegistration().setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new StudentAttendance().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ManageGrades().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ViewGrades().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ViewReport().setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ViewTeachers().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         setVisible(false);
        new TeacherLogin().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jComboLevel;
    private javax.swing.JComboBox<String> jComboRemarks;
    private javax.swing.JComboBox<String> jComboStudentID;
    private javax.swing.JComboBox<String> jComboStudentName;
    private javax.swing.JComboBox<String> jComboTeacherName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAgric;
    private javax.swing.JTextField txtChemistry;
    private javax.swing.JTextField txtComputer;
    private javax.swing.JTextField txtEconomics;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtFutherMath;
    private javax.swing.JTextField txtGeography;
    private javax.swing.JTextField txtIrs;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtPhysics;
    private javax.swing.JTextField txtTotalScore;
    // End of variables declaration//GEN-END:variables
}
