
package sis;

import dao.ConnectionProvider;
import dao.DbOperations;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Academic;

/**
 *
 * @author AmTechGuy
 */
public class ViewGrades extends javax.swing.JFrame {

    /**
     * Creates new form ViewGrades
     */
    public ViewGrades() {
        initComponents();
        txtTotalScore.setEditable(false);
    }
    
    public void clear(){
         txtMath.setText("");
         txtComputer.setText("");
         txtPhysics.setText("");
         txtChemistry.setText("");
         txtFutherMath.setText("");
         txtEnglish.setText("");
         txtEconomics.setText("");
         txtGeography.setText("");
         txtIrs.setText("");
         txtAgric.setText("");
         txtTotalScore.setText("");
     }
//     public void clear(){
//         txtMath.setText("");
//         txtComputer.setText("");
//         txtPhysics.setText("");
//         txtChemistry.setText("");
//         
//     }
    public void computeScores() {
    try {
        int math = Integer.parseInt(txtMath.getText());
        int computer = Integer.parseInt(txtComputer.getText());
        int physics = Integer.parseInt(txtPhysics.getText());
        int chemistry = Integer.parseInt(txtChemistry.getText());
        int further = Integer.parseInt(txtFutherMath.getText());
        int english = Integer.parseInt(txtEnglish.getText());
        int economics = Integer.parseInt(txtEconomics.getText());
        int geography = Integer.parseInt(txtGeography.getText());
        int irs = Integer.parseInt(txtIrs.getText());
        int agric = Integer.parseInt(txtAgric.getText());

        int totalScore = math + computer + physics + chemistry + further + english + economics
                + geography + irs + agric;

        String score = String.format("%d", totalScore);
        txtTotalScore.setText(score);
    } catch (NumberFormatException e) {
        txtTotalScore.setText("Invalid input");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtFutherMath = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtEnglish = new javax.swing.JTextField();
        txtEconomics = new javax.swing.JTextField();
        txtGeography = new javax.swing.JTextField();
        txtIrs = new javax.swing.JTextField();
        txtAgric = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtTotalScore = new javax.swing.JTextField();
        txtMath = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtComputer = new javax.swing.JTextField();
        txtPhysics = new javax.swing.JTextField();
        txtChemistry = new javax.swing.JTextField();
        txtRemarks = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Information System");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 1284, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/imagesIcon.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout.png"))); // NOI18N
        jLabel7.setText("Logout");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Home");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Register Student");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mark Attendance");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Academic Record");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("View Academic Records");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("View Report/Complains");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("View Registered Teachers");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 72, 278, 705));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher Name", "Student ID", "Student Name", "Student Level", "Mathematics", "Computer Sci", "Physics", "Chemistry", "Further Math", "English", "Economics", "Geography", "IRS", "Agric", "Total Score", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 102, 950, 152));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel15.setText("Remarks");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 520, -1, -1));

        txtFutherMath.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFutherMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFutherMathKeyReleased(evt);
            }
        });
        getContentPane().add(txtFutherMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 478, 190, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel29.setText("Geography");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 377, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel30.setText("Agric");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 481, -1, -1));

        txtEnglish.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtEnglish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnglishKeyReleased(evt);
            }
        });
        getContentPane().add(txtEnglish, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 266, 190, -1));

        txtEconomics.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtEconomics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEconomicsKeyReleased(evt);
            }
        });
        getContentPane().add(txtEconomics, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 326, 190, -1));

        txtGeography.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtGeography.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGeographyKeyReleased(evt);
            }
        });
        getContentPane().add(txtGeography, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 374, 190, -1));

        txtIrs.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtIrs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIrsKeyReleased(evt);
            }
        });
        getContentPane().add(txtIrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 424, 190, -1));

        txtAgric.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtAgric.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgricKeyReleased(evt);
            }
        });
        getContentPane().add(txtAgric, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 478, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel14.setText("Mathematics");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 276, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel17.setText("Computer Sci.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 329, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel31.setText("English");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 276, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel32.setText("Economics");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 329, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setText("Physics");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 385, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel33.setText("IRS");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 428, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel24.setText("Chemistry");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 431, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel27.setText("Futher Math");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 481, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 578, -1, -1));

        txtTotalScore.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtTotalScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalScoreMouseClicked(evt);
            }
        });
        txtTotalScore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalScoreKeyReleased(evt);
            }
        });
        getContentPane().add(txtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 517, 190, -1));

        txtMath.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtMath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMathKeyReleased(evt);
            }
        });
        getContentPane().add(txtMath, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 276, 190, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel28.setText("Total Score");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 520, -1, -1));

        txtComputer.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtComputer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtComputerKeyReleased(evt);
            }
        });
        getContentPane().add(txtComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 329, 190, -1));

        txtPhysics.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtPhysics.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhysicsKeyReleased(evt);
            }
        });
        getContentPane().add(txtPhysics, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 374, 190, -1));

        txtChemistry.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtChemistry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtChemistryKeyReleased(evt);
            }
        });
        getContentPane().add(txtChemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 428, 190, -1));

        txtRemarks.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtRemarks.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRemarksKeyReleased(evt);
            }
        });
        getContentPane().add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 517, 190, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 102));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(1161, 266, -1, -1));

        btnClear.setBackground(new java.awt.Color(0, 0, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(736, 578, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1143, 321, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        //Report report = null;
        try{
            ResultSet res = DbOperations.getData("select * from academics");
            while(res.next()){
                String [] obj = new String[16];
                obj[0] = res.getString("techerName");
                obj[1] = res.getString("studentId");
                obj[2] = res.getString("studentName");
                obj[3] = res.getString("studentLevel");
                obj[4] = res.getString("mathematics");
                obj[5]= res.getString("computerSci");
                obj[6] = res.getString("physics");
                obj[7] = res.getString("chemistry");
                obj[8] = res.getString("furtherMath");
                obj[9] = res.getString("english");
                obj[10] = res.getString("economics");
                obj[11] = res.getString("geography");
                obj[12] = res.getString("irs");
                obj[13] = res.getString("agric");
                obj[14] = res.getString("total");
                obj[15] = res.getString("remarks");
                model.addRow(obj);
                //dispose();
            }

        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void txtFutherMathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFutherMathKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtFutherMathKeyReleased

    private void txtEnglishKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnglishKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtEnglishKeyReleased

    private void txtEconomicsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEconomicsKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtEconomicsKeyReleased

    private void txtGeographyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGeographyKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtGeographyKeyReleased

    private void txtIrsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIrsKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtIrsKeyReleased

    private void txtAgricKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgricKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtAgricKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
//        String teacherName = jComboTeacherName.getSelectedItem().toString();
//        String studentId = jComboStudentID.getSelectedItem().toString();
//        String studentName = jComboStudentName.getSelectedItem().toString();
//        String level = jComboLevel.getSelectedItem().toString();
        String math = txtMath.getText();
        String computer = txtComputer.getText();
        String physics = txtPhysics.getText();
        String chemistry = txtChemistry.getText();
        String further = txtFutherMath.getText();
        String english = txtEnglish.getText();
        String economics = txtEconomics.getText();
        String geography = txtGeography.getText();
        String irs = txtIrs.getText();
        String agric = txtAgric.getText();
        String total = txtTotalScore.getText();
        String remarks = txtRemarks.getText();
        try{
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            if(jTable1.getSelectedRowCount() != -1){
                model.setValueAt(math, jTable1.getSelectedRow(), 4);
                model.setValueAt(computer, jTable1.getSelectedRow(), 5);
                model.setValueAt(physics,jTable1.getSelectedRow(), 6);
                model.setValueAt(chemistry, jTable1.getSelectedRow(), 7);
                model.setValueAt(further, jTable1.getSelectedRow(), 8);
                model.setValueAt(english, jTable1.getSelectedRow(), 9);
                model.setValueAt(economics, jTable1.getSelectedRow(), 10);
                model.setValueAt(geography, jTable1.getSelectedRow(), 11);
                model.setValueAt(irs, jTable1.getSelectedRow(), 12);
                model.setValueAt(agric, jTable1.getSelectedRow(), 13);
                model.setValueAt(total, jTable1.getSelectedRow(), 14);
                model.setValueAt(remarks, jTable1.getSelectedRow(), 15);
            }
//            Object [] obj = new Object[16];
//            obj[4] = math;
//            obj[5] = computer;
//            obj[6] = physics;
//            obj[7] = chemistry;
//            obj[8] = further;
//            obj[9] = english;
//            obj[10] = economics;
//            obj[11] = geography;
//            obj[12] = irs;
//            obj[13] = agric;
//            obj[14] = total;
//            obj[15] = remarks;
//
//            model.addRow(obj);
//            clear();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtTotalScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalScoreMouseClicked
        // TODO add your handling code here:
        computeScores();
    }//GEN-LAST:event_txtTotalScoreMouseClicked

    private void txtTotalScoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalScoreKeyReleased
        // TODO add your handling code here:
        //validates();
        computeScores();
    }//GEN-LAST:event_txtTotalScoreKeyReleased

    private void txtMathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMathKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtMathKeyReleased

    private void txtComputerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComputerKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtComputerKeyReleased

    private void txtPhysicsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhysicsKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtPhysicsKeyReleased

    private void txtChemistryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChemistryKeyReleased
        // TODO add your handling code here:
        //validates();
    }//GEN-LAST:event_txtChemistryKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          //Academic academic =  new Academic();
          int index = jTable1.getSelectedRow();
          DefaultTableModel  model = (DefaultTableModel)jTable1.getModel();
          //String m = academic.setMath(model.getValueAt(index, 4).toString());
          String math = model.getValueAt(index, 4).toString();
          String computer = model.getValueAt(index, 5).toString();
          String physics = model.getValueAt(index, 6).toString();
          String chemistry = model.getValueAt(index, 7).toString();
          String furtherMath = model.getValueAt(index, 8).toString();
          String english = model.getValueAt(index, 9).toString();
          String economics = model.getValueAt(index, 10).toString();
          String geography = model.getValueAt(index, 11).toString();
          String irs = model.getValueAt(index, 12).toString();
          String agric = model.getValueAt(index, 13).toString();
          String total = model.getValueAt(index, 14).toString();
          String remarks = model.getValueAt(index, 15).toString();
          
          txtMath.setText(math);
          txtComputer.setText(computer);
          txtPhysics.setText(physics);
          txtChemistry.setText(chemistry);
          txtFutherMath.setText(furtherMath);
          txtEnglish.setText(english);
          txtEconomics.setText(economics);
          txtGeography.setText(geography);
          txtIrs.setText(irs);
          txtAgric.setText(agric);
          txtTotalScore.setText(total);
          txtRemarks.setText(remarks);
          
          
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtRemarksKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRemarksKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemarksKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here
        int index = jTable1.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        try{ 
            for(int i = 0; i<jTable1.getRowCount(); i++){
//                String teacherName = model.getValueAt(i, 0).toString();
                  String studentId = model.getValueAt(i, 1).toString();
//                String studentName = model.getValueAt(i, 2).toString();
//                String studentLevel = model.getValueAt(i, 3).toString();
                String math = model.getValueAt(i, 4).toString();
                String computerSci = model.getValueAt(i, 5).toString();
                String physics = model.getValueAt(i, 6).toString();
                String chemistry = model.getValueAt(i, 7).toString();
                String further = model.getValueAt(i, 8).toString();
                String english = model.getValueAt(i, 9).toString();
                String economics = model.getValueAt(i, 10).toString();
                String geo = model.getValueAt(i, 11).toString();
                String irs = model.getValueAt(i, 12).toString();
                String agric = model.getValueAt(i, 13).toString();
                String total = model.getValueAt(i, 14).toString();
                String remarks = model.getValueAt(i, 15).toString();
                
                String query = "update academics set mathematics = '"+math+"', computerSci = '"+computerSci+"', "
                        + "physics = '"+physics+"', chemistry ='"+chemistry+"', furtherMath = '"+further+"', "
                        + "english = '"+english+"', economics = '"+economics+"', geography = '"+geo+"',irs = '"+irs+"',"
                        + "agric = '"+agric+"', total = '"+total+"', remarks = '"+remarks+"' where studentId = '"+studentId+"'";
                Connection connection = ConnectionProvider.getCon();
                PreparedStatement ps = connection.prepareStatement(query);
                ps.execute();
               
            }
             JOptionPane.showMessageDialog(null, "Records Saved!!");
            
            
            setVisible(false);
            new ViewGrades().setVisible(true);
        }
        catch(Exception e){
            e.printStackTrace();
             JOptionPane.showMessageDialog(null, "Error updating records!!");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
                int index = jTable1.getSelectedRow();
                TableModel model = jTable1.getModel();
                String studentId = model.getValueAt(index, 1).toString();
                String studentName = model.getValueAt(index, 2).toString();
                 int a = JOptionPane.showConfirmDialog(null, "Do you really want to delete "+studentName+" records from database?", 
                "Select", JOptionPane.YES_NO_OPTION);
                 try {
                    if(a == 0){

                        String query = "delete from academics where studentId='"+studentId+"'";
                        Connection connection = ConnectionProvider.getCon();
                        PreparedStatement ps = connection.prepareStatement(query);
                        ps.execute();
                        JOptionPane.showMessageDialog(null, "Record Deleted!!");
                        setVisible(false);
                        new ViewGrades().setVisible(true);
                    } 
                    }
                    catch (SQLException ex) {
                       ex.printStackTrace();
       
                    }
               
               
            
            
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        setVisible(false);
        new TeacherDashBoard().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new StudentRegistration().setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new StudentAttendance().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ManageGrades().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ViewGrades().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ViewReport().setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        setVisible(false);
        new ViewTeachers().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
         setVisible(false);
        new TeacherLogin().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAgric;
    private javax.swing.JTextField txtChemistry;
    private javax.swing.JTextField txtComputer;
    private javax.swing.JTextField txtEconomics;
    private javax.swing.JTextField txtEnglish;
    private javax.swing.JTextField txtFutherMath;
    private javax.swing.JTextField txtGeography;
    private javax.swing.JTextField txtIrs;
    private javax.swing.JTextField txtMath;
    private javax.swing.JTextField txtPhysics;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtTotalScore;
    // End of variables declaration//GEN-END:variables
}
